import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'
import SessionAuthProvider from '../../context/SessionAuthProvider'
import NavBar from '../../components/NavBar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <main className="contaniner">
          
          <SessionAuthProvider>
          <NavBar />
            {children}
          </SessionAuthProvider>
        </main>
      
      </body>
    </html>
  );
}
